"""Email Automation Payload Processor Module.

Processes incoming email webhooks (e.g. from n8n or SendGrid), extracts question queries,
queries the RAG pipeline, and constructs structured email response drafts.
"""

import logging
from dataclasses import dataclass
from typing import Any, Dict

from rag.pipeline import RAGPipeline

logger = logging.getLogger(__name__)


@dataclass
class EmailPayload:
    """Dataclass representing incoming email payload.

    Attributes:
        sender: Email address of sender.
        subject: Subject line string.
        body: Text body of email containing the ML question.
        message_id: Unique email message ID string.
    """

    sender: str
    subject: str
    body: str
    message_id: str


class EmailRAGProcessor:
    """Processes incoming email queries and generates RAG responses for n8n integration."""

    def __init__(self, rag_pipeline: RAGPipeline | None = None) -> None:
        """Initializes email processor with RAG pipeline.

        Args:
            rag_pipeline: RAGPipeline instance.
        """
        self.rag_pipeline = rag_pipeline or RAGPipeline()
        logger.info("EmailRAGProcessor initialized.")

    def process_email(self, payload: EmailPayload) -> Dict[str, Any]:
        """Processes an incoming email payload and returns response email dictionary.

        Args:
            payload: EmailPayload object.

        Returns:
            Dictionary containing reply email recipient, subject, body, and sources.
        """
        logger.info("Processing automated email query from: %s", payload.sender)

        # 1. Execute RAG query on email body text
        rag_result = self.rag_pipeline.run(query=payload.body)

        # 2. Build reply email content
        reply_subject = f"Re: {payload.subject}"
        formatted_sources = "\n".join([f"- {s.filename} (Page {s.page_number})" for s in rag_result.sources])

        reply_body = (
            f"Hello,\n\n"
            f"Here is the answer to your Machine Learning inquiry:\n\n"
            f"{rag_result.answer}\n\n"
            f"--------------------------------------------------\n"
            f"Confidence Score: {rag_result.confidence_score * 100:.1f}%\n"
            f"Sources Cited:\n{formatted_sources if formatted_sources else 'N/A'}\n"
            f"--------------------------------------------------\n"
            f"Automated response generated by ML RAG Agent."
        )

        logger.info("Email response constructed successfully for message ID: %s", payload.message_id)

        return {
            "recipient": payload.sender,
            "subject": reply_subject,
            "body": reply_body,
            "confidence_score": rag_result.confidence_score,
            "message_id": payload.message_id,
        }
